version: 2
updates:
  - package-ecosystem: npm
    directory: /c4ify
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
